### PR TITLE
Keyboard selector

### LINKED ISSUE #7: App needs some sort of keyboard selector
It would be nice if the app had a keyboard selector menu option.

### PR DESCRIPTION
**Pull request by donniebreve**
Added a keyboard selector and some menu items.

image

Closes #7

### CODE REVIEW

**Review by jasonmlkang — APPROVED** [review]
Been using it for a day with macbook pro internal keyboard and it works great!

I have following problems but mostly related to my system:
* I cannot compile the latest code because you updated the project to xcode v13 at [this](https://github.com/donniebreve/touchcursor-mac/pull/14/commits/9aae3b281370274d6a167effa488fcaf30143d4a) (github.com) commit, I think. Xcode v13 requires MacOS 11, but I cannot update to MacOS 11 at this point. So I had to revert to [this](https://github.com/donniebreve/touchcursor-mac/pull/14/commits/ef029a37296b07a6ad61eb444c77248b987fa220) (github.com) commit inorder for it to work in my env.
* in my env, I always have one device that conforms to a keyboard but will school up the `CFStringCreateCopy` in `getKeyboardList`. I notice that device does not have a product name, so I ended up excluding the device from keyboard list like this:

```
// Check if the device is a keyboard, this also opens the device
if ( getProductName(devices[i], buffer, 256) > 0 && 
      IOHIDDeviceConformsTo(devices[i], kHIDPage_GenericDesktop, kHIDUsage_GD_Keyboard) )
```

**Comment by donniebreve** [comment]
I think the project upgrade was done when trying to get my project to run. Xcode just behaves strangely sometimes. We can revert the project back to whatever Xcode version you can support. Maybe just make sure you update Xcode before checking which versions you can select in this dropdown.

image

For the keyboard, maybe we can insert "Unknown" or something if it doesn't have a product name.

**Comment by jasonmlkang** [comment]
@donniebreve 
I tested out your latest commit. First of all, I'm able to compile the code after you down-graded the project to xcode v12. Thank you! I also notice the unknown device gets picked up and is no longer causing any issues.

Two additional issues I found:
* Statusbar image is not showing up (see screenshoot below). This time, it is not caused by corrupted image file, but it is something else (possible project files). I spent couple hours debugging this but I still can't find the problem. I will continue to look into it this week.
image
* I suspect there is a memory leak somewhere. I notice memory usage would go steadily up and would never come back down (see screenshoot below). You probably want to look into this one.
touchcursor-possible-memory-leak

**Comment by donniebreve** [comment]
Those images are a pain... Xcode is a pain...

As far as the memory leak, looks like it might come from opening the status bar menu a lot? In my attempts the memory drops back down to ~16mb, so maybe it's the new code with the Unknown name.

**Comment by jasonmlkang** [comment]
For the memory issue, in my case, it stays at 21.9MB to 22MB even if I don't touch the status bar. But maybe that is just the amount of memory it needs to operate. It does not go beyond that and the system does not throw memory exceptions.

FYI, I'm using it with a external keyboard and it work fine!

**Pull request merged**
